### ISSUE TITLE
no binary after installing

### ISSUE THREAD

**Issue by paulmil1** [oshosanya/graphql-export#2]
![image](https://user-images.githubusercontent.com/38671110/75427934-aab8a880-5947-11ea-82a8-0b178b55a815.png)

doesnt build properly,  NCC fails - it has to be installed, but after that still fails
![image](https://user-images.githubusercontent.com/38671110/75428025-d045b200-5947-11ea-8cec-d942b82d6591.png)

**Comment by oshosanya** [comment]
You can reinstall using npm, problem has been fixed
