### ISSUE TITLE
How get schema with x-hasura-admin-secret

### ISSUE THREAD

**Issue by eDubrovsky** [oshosanya/graphql-export#5]
At first, thank you for the cool tool! 

If my graphql endpoint protected with the admin secret, how I can use your script?

**Comment by oshosanya** [comment]
I don't use graphql much, but i'll see what i could do. If you know how to, you can also create a pull request

**Comment by Mayur1995** [comment]
Thanks, man, this is a pretty awesome tool, but yes I do agree with having some additional functionality for adding custom headers as most of the time it is protected by authentication headers. Please update here once this is available.

**Comment by oshosanya** [comment]
The requested feature has been implemented. On version 1.0.6, you can update and try it out
