### ISSUE TITLE
Empty export.

### ISSUE THREAD

**Issue by berkaytheunicorn** [oshosanya/graphql-export#7]
Hi, I just tried this with insomnia and it always creates empty json file. No mutations or queries, nothing. BTW, also won't export as postman json.

**Comment by mian-muhammad** [comment]
@berkaey same here.

**Comment by oshosanya** [comment]
A fix is in the works, there's already a pull request for it and it'll be merged soon

**Comment by oshosanya** [comment]
Newest version fixes that

**Comment by renepardon** [comment]
Got the same issue. @oshosanya 
Saw that package and thought: nice! But then for insomnia and postman it looks like:

```
{
    "info": {
        "name": "https://api.whatever.com/graphql",
        "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
    },
    "item": [],
    "variable": [
        {
            "key": "base_url",
            "value": "https://api.whatever.com/graphql"
        }
    ]
}%  
```

Yes, there is a percentage sign at the end and there are no queries and mutations being exportet. I run this on Ubuntu 20 with Yarn 1.22.10.

Got the same result running with Authorization header and without

**Comment by oshosanya** [comment]
You might need to specify the name of your root mutation and query types. By default, it uses `RootMutationType` and `RootQueryType` respectively.
 
 So your command will be something like
 
 `graphql-export -u https://api.whatever.com/graphql -q QueryTypeName -m MutationTypeName`

> Got the same issue. @oshosanya
> Saw that package and thought: nice! But then for insomnia and postman it looks like:
> 
> ```
> {
>     "info": {
>         "name": "https://api.whatever.com/graphql",
>         "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
>     },
>     "item": [],
>     "variable": [
>         {
>             "key": "base_url",
>             "value": "https://api.whatever.com/graphql"
>         }
>     ]
> }%  
> ```
> 
> Yes, there is a percentage sign at the end and there are no queries and mutations being exportet. I run this on Ubuntu 20 with Yarn 1.22.10.
> 
> Got the same result running with Authorization header and without
